config/routes.rb
Rails.application.routes.draw do

  get 'schedule/index'

  get 'schedule/p1'

  get 'schedule/p2'

  get "/courses/sort " => "courses#sort", :as => 'sort'

  get 'prof/index'

  get 'prof/list'

  get 'prof/show'

  get 'prof/new'
  resources :faculties

  resources :courses
  resources  :welcome

  get 'url_construct/index'
  match ':controller(/:action(/:id))', :via => :get
  match ':controller(/:action(/:id))', :via => :post

  get 'admin/new'

  get 'admin/become_admin_attempt'
  post 'admin/become_admin_attempt'

  get 'sessions/login'
  post 'sessions/login_attempt'
  get 'sessions/logout'

  get 'users/login'
  get 'users/new'
  get 'welcome/index'

  resources :users

  root 'welcome#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_and_belongs_to_many :user
  has_many :tutorial

  def self.search(faculty, number, year,semester, unit, prof, w,q,b, mon, tu, wed, th, fri)

    if faculty || number || year || semester || unit || prof ||  w || q || b || mon || tu || wed || th || fri #|| section || instructor || unit

     where(['faculty LIKE ? AND number LIKE ? AND year LIKE ? AND semester LIKE ? AND unit LIKE ? AND instructor LIKE ? AND designation LIKE ?  AND designation LIKE ?  AND designation LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?',
      "%#{faculty}%", "%#{number}%", "%#{year}%", "%#{semester}%", "%#{unit}%", "%#{prof}%" ,"%#{w}%" ,"%#{q}%","%#{b}%","%#{mon}%","%#{tu}%","%#{wed}%","%#{th}%","%#{fri}%" ]) #, "%#{unit}%", "%#{designation}%"  ])
    else
      self.all
    end
  end


end

app/models/d_course.rb
class DCourse < ActiveRecord::Base
  belongs_to :DFaculty
end

app/models/d_detail.rb
class DDetail < ActiveRecord::Base
end

app/models/d_faculty.rb
class DFaculty < ActiveRecord::Base
  belongs_to :DSemester
  has_many :DCourses
end

app/models/d_section.rb
class DSection < ActiveRecord::Base
end

app/models/d_semester.rb
class DSemester < ActiveRecord::Base
  belongs_to :DYear
  has_many :DFaculties
end

app/models/d_year.rb
class DYear < ActiveRecord::Base
  has_many :DSemesters
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	 validates_length_of :prof_name, :in => 3..20
	 validates :user_name, :presence => true, :length => { :in => 3..20 }

	 validates :rating, numericality: { only_integer: true, allow_blank: true} 
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  belongs_to :course
  has_and_belongs_to_many :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :course
  has_and_belongs_to_many :tutorial
  attr_accessor :password

  EMAIL_REGEX =  /\A[^@\s]+@([^@.\s]+\.)*[^@.\s]+\z/
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create

  before_save :encrypt_password
  after_save :clear_password
  def encrypt_password
	if password.present?
    	self.salt = BCrypt::Engine.generate_salt
    	self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
  	end
  end

  def clear_password
     self.password = nil
  end

  def self.authenticate(username_or_email="", login_password="")
    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end
    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
	
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/prof_helper.rb
module ProfHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sort_helper.rb
module SortHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/new.html.erb
<% @page_title = "AdminAuth | SignUp" %>

<div class= "Sign_Form">
  <h1>Admin Authentication Form</h1>
  <%= form_tag(:action => 'become_admin_attempt') do %>
    
    <p>Admin Password:</br> <%= password_field_tag :admin_password%></p> 

    <%= submit_tag("Authenticate") %>
    <br><br>
    <span class= "back-button"><%= link_to 'Back', welcome_index_path%></span>
  <% end %>

  <p id="notice"><%= notice %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SfuPlanner</title>
  <link rel="icon" href="http://www.mrsnelsons.com/sites/mrsnelsons.com/files/books.jpg" type="image/x-icon" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <div class="toolbar">
  <ul>
    <li><a class = "upper-button" href="/welcome">Search</a></li>
    <li><a class = "upper-button" href="/users/show">Profile</a></li>
    <li><a class = "upper-button" href="/schedule">Schedule</a></li>
    <li><a class = "upper-button" href="/prof">Rate a Professor</a></li>

    <% if session[:user_name].present? %>
  		<li style="float:right"><a class = "upper-button" href= "/sessions/logout">Logout</a></li>
      <li style="float:right"><a class = "name-button" ><%=session[:user_name]%></a><li>

      <% if session[:is_admin] %>
        <li style="float:right"><a class = "upper-button" href="/users"> Show User </a></li>
        <li  style="float:right"><a class = "upper-button" href="/urlConstruct"> urlConstruct </a></li>
      <% else %>
        <li style="float:right"><a class = "upper-button" href="/admin/new"> Become Admin</a></li>
      <% end %>
  	<% else %>
  		<li style="float:right"><a class = "upper-button" href= "/users/new">Sign Up</a></li>
  		<li style="float:right"><a class = "upper-button" href= "/sessions/login"> Login </a></li>
  	<% end %>
  </ul>
  </div>
</head>
<body>

<%= yield %>

</body>
</html>