config/routes.rb
Rails.application.routes.draw do

  get 'schedule/index'

  get 'schedule/p1'

  get 'schedule/p2'

  get "/courses/sort " => "courses#sort", :as => 'sort'

  get 'prof/index'

  get 'prof/list'

  get 'prof/show'

  get 'prof/new'
  resources :faculties

  resources :courses
  resources  :welcome

  get 'url_construct/index'
  match ':controller(/:action(/:id))', :via => :get
  match ':controller(/:action(/:id))', :via => :post

  get 'admin/new'

  get 'admin/become_admin_attempt'
  post 'admin/become_admin_attempt'

  get 'sessions/login'
  post 'sessions/login_attempt'
  get 'sessions/logout'

  get 'users/login'
  get 'users/new'
  get 'welcome/index'

  resources :users

  root 'welcome#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_and_belongs_to_many :user
  has_many :tutorial

  def self.search(faculty, number, year,semester, unit, prof, w,q,b, mon, tu, wed, th, fri)

    if faculty || number || year || semester || unit || prof ||  w || q || b || mon || tu || wed || th || fri #|| section || instructor || unit

     where(['faculty LIKE ? AND number LIKE ? AND year LIKE ? AND semester LIKE ? AND unit LIKE ? AND instructor LIKE ? AND designation LIKE ?  AND designation LIKE ?  AND designation LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?',
      "%#{faculty}%", "%#{number}%", "%#{year}%", "%#{semester}%", "%#{unit}%", "%#{prof}%" ,"%#{w}%" ,"%#{q}%","%#{b}%","%#{mon}%","%#{tu}%","%#{wed}%","%#{th}%","%#{fri}%" ]) #, "%#{unit}%", "%#{designation}%"  ])
    else
      self.all
    end
  end


end

app/models/d_course.rb
class DCourse < ActiveRecord::Base
  belongs_to :DFaculty
end

app/models/d_detail.rb
class DDetail < ActiveRecord::Base
end

app/models/d_faculty.rb
class DFaculty < ActiveRecord::Base
  belongs_to :DSemester
  has_many :DCourses
end

app/models/d_section.rb
class DSection < ActiveRecord::Base
end

app/models/d_semester.rb
class DSemester < ActiveRecord::Base
  belongs_to :DYear
  has_many :DFaculties
end

app/models/d_year.rb
class DYear < ActiveRecord::Base
  has_many :DSemesters
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	 validates_length_of :prof_name, :in => 3..20
	 validates :user_name, :presence => true, :length => { :in => 3..20 }

	 validates :rating, numericality: { only_integer: true, allow_blank: true} 
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  belongs_to :course
  has_and_belongs_to_many :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :course
  has_and_belongs_to_many :tutorial
  attr_accessor :password

  EMAIL_REGEX =  /\A[^@\s]+@([^@.\s]+\.)*[^@.\s]+\z/
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create

  before_save :encrypt_password
  after_save :clear_password
  def encrypt_password
	if password.present?
    	self.salt = BCrypt::Engine.generate_salt
    	self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
  	end
  end

  def clear_password
     self.password = nil
  end

  def self.authenticate(username_or_email="", login_password="")
    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end
    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
	
	def index
      @faculties = Faculty.all
  	end

	def show
    	@faculty = Faculty.find(params[:id])
  	end

  	def new
  		
  	end


  	def edit
     	@faculty = Faculty.find(params[:id])
  	end  


	def update
    	@faculty = Faculty.find(params[:id])

    	if @faculty.update(faculty_params)
     	 	redirect_to @faculty
    	else
      		render 'edit'
    	end
  	end


	def create
  		@faculty = Faculty.new(faculty_params)
 
  		if @faculty.save
  			redirect_to @faculty
  		else
  			render 'new'
  		end
	end


	def destroy
  		@faculty = Faculty.find(params[:id])
  		@faculty.destroy
  		redirect_to faculties_path
	end

	private
    	def faculty_params
      		params.require(:faculty).permit(:name, :description)
    	end
end

app/controllers/prof_controller.rb
class ProfController < ApplicationController
  	def index
  		if params[:page]
  			@current_page = params[:page].to_i
  		else
  			@current_page = 1
  		end

		prof_name = params[:prof_name]
		if prof_name
			prof_name.downcase!
		end

		@profs = Course.where("LOWER(instructor) LIKE ?", "%#{prof_name}%")

	  	# get unique instructor names
	  	@profs = @profs.uniq.pluck(:instructor) 
	  	
	  	# sort
	  	@profs = @profs.sort! 

	  	@pages_count = @profs.length / 10.0
	  	@pages_count = @pages_count.ceil

	  	@profs = @profs.drop((@current_page - 1) * 10)
	  	@profs = @profs.take 10
	end

	def list
		prof_name = params[:prof_name]
		if prof_name
			prof_name.downcase!
		end

		@profs = Course.where("LOWER(instructor) LIKE ?", "%#{prof_name}%")

	  	# get unique instructor names
	  	@profs = @profs.uniq.pluck(:instructor) 
	  	
	  	# sort
	  	@profs = @profs.sort!
	end

	def show
		@ratings = Rating.where(prof_name: params[:prof_name])

		@ratings_total = 0
		@ratings_count = 0

		@ratings.each do |rating|
			if rating.rating
				@ratings_total += rating.rating
				@ratings_count += 1
			end
		end

		@rating_average = @ratings_total.to_f / @ratings_count
		@rating_average = @rating_average.round(2)
	end

	def new
		# delete previous comment for this prof from this user
		Rating.where(:prof_name => params[:prof_name], :user_name => session[:user_name]).destroy_all

		@rating = Rating.new
		@rating[:comment] = params[:comment]
		@rating[:rating] = params[:rating]
		@rating[:prof_name] = params[:prof_name]
		@rating[:user_name] = session[:user_name]

		@rating.save

		redirect_to action: "show", prof_name: params[:prof_name]
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
	
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/prof_helper.rb
module ProfHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sort_helper.rb
module SortHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/faculties/edit.html.erb
<h1>Editing faculty</h1>

<%= form_for :faculty, url: faculty_path(@faculty), method: :patch do |f| %>


  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<h1>Listing faculties</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
     <th colspan="3"></th>
  </tr>
 
  <% @faculties.each do |faculty| %>
    <tr>
      <td><%= faculty.name %></td>
      <td><%= faculty.description %></td>
      <td><%= link_to 'Show', faculty_path(faculty) %></td>
      <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
      <td><%= link_to 'Destroy', faculty_path(faculty),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
 <%= link_to 'New faculty', new_faculty_path %>

app/views/faculties/new.html.erb
<h1>new faculty</h1>


<%= form_for :faculty, url: faculties_path do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<table>
<tr>
<th> <strong>Name:</strong> </th>
<th> <strong>Description:</strong> </th>
</tr>

<tr>
  <td><%= @faculty.name %></td>
  <td><%= @faculty.description %></td>
</tr>
</table>
<h3> listing courses: </h3>
<% @faculty.courses.each do |course| %>

<%= render partial:'courses/course', locals: { course: course }  %>

<% end %>
<h3> add course: </h3>
<%= render 'courses/form' %>

<%= link_to 'back', faculties_path %>