config/routes.rb
Rails.application.routes.draw do

  get 'schedule/index'

  get 'schedule/p1'

  get 'schedule/p2'

  get "/courses/sort " => "courses#sort", :as => 'sort'

  get 'prof/index'

  get 'prof/list'

  get 'prof/show'

  get 'prof/new'
  resources :faculties

  resources :courses
  resources  :welcome

  get 'url_construct/index'
  match ':controller(/:action(/:id))', :via => :get
  match ':controller(/:action(/:id))', :via => :post

  get 'admin/new'

  get 'admin/become_admin_attempt'
  post 'admin/become_admin_attempt'

  get 'sessions/login'
  post 'sessions/login_attempt'
  get 'sessions/logout'

  get 'users/login'
  get 'users/new'
  get 'welcome/index'

  resources :users

  root 'welcome#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_and_belongs_to_many :user
  has_many :tutorial

  def self.search(faculty, number, year,semester, unit, prof, w,q,b, mon, tu, wed, th, fri)

    if faculty || number || year || semester || unit || prof ||  w || q || b || mon || tu || wed || th || fri #|| section || instructor || unit

     where(['faculty LIKE ? AND number LIKE ? AND year LIKE ? AND semester LIKE ? AND unit LIKE ? AND instructor LIKE ? AND designation LIKE ?  AND designation LIKE ?  AND designation LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?',
      "%#{faculty}%", "%#{number}%", "%#{year}%", "%#{semester}%", "%#{unit}%", "%#{prof}%" ,"%#{w}%" ,"%#{q}%","%#{b}%","%#{mon}%","%#{tu}%","%#{wed}%","%#{th}%","%#{fri}%" ]) #, "%#{unit}%", "%#{designation}%"  ])
    else
      self.all
    end
  end


end

app/models/d_course.rb
class DCourse < ActiveRecord::Base
  belongs_to :DFaculty
end

app/models/d_detail.rb
class DDetail < ActiveRecord::Base
end

app/models/d_faculty.rb
class DFaculty < ActiveRecord::Base
  belongs_to :DSemester
  has_many :DCourses
end

app/models/d_section.rb
class DSection < ActiveRecord::Base
end

app/models/d_semester.rb
class DSemester < ActiveRecord::Base
  belongs_to :DYear
  has_many :DFaculties
end

app/models/d_year.rb
class DYear < ActiveRecord::Base
  has_many :DSemesters
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	 validates_length_of :prof_name, :in => 3..20
	 validates :user_name, :presence => true, :length => { :in => 3..20 }

	 validates :rating, numericality: { only_integer: true, allow_blank: true} 
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  belongs_to :course
  has_and_belongs_to_many :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :course
  has_and_belongs_to_many :tutorial
  attr_accessor :password

  EMAIL_REGEX =  /\A[^@\s]+@([^@.\s]+\.)*[^@.\s]+\z/
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create

  before_save :encrypt_password
  after_save :clear_password
  def encrypt_password
	if password.present?
    	self.salt = BCrypt::Engine.generate_salt
    	self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
  	end
  end

  def clear_password
     self.password = nil
  end

  def self.authenticate(username_or_email="", login_password="")
    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end
    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

end

app/controllers/prof_controller.rb
class ProfController < ApplicationController
  	def index
  		if params[:page]
  			@current_page = params[:page].to_i
  		else
  			@current_page = 1
  		end

		prof_name = params[:prof_name]
		if prof_name
			prof_name.downcase!
		end

		@profs = Course.where("LOWER(instructor) LIKE ?", "%#{prof_name}%")

	  	# get unique instructor names
	  	@profs = @profs.uniq.pluck(:instructor) 
	  	
	  	# sort
	  	@profs = @profs.sort! 

	  	@pages_count = @profs.length / 10.0
	  	@pages_count = @pages_count.ceil

	  	@profs = @profs.drop((@current_page - 1) * 10)
	  	@profs = @profs.take 10
	end

	def list
		prof_name = params[:prof_name]
		if prof_name
			prof_name.downcase!
		end

		@profs = Course.where("LOWER(instructor) LIKE ?", "%#{prof_name}%")

	  	# get unique instructor names
	  	@profs = @profs.uniq.pluck(:instructor) 
	  	
	  	# sort
	  	@profs = @profs.sort!
	end

	def show
		@ratings = Rating.where(prof_name: params[:prof_name])

		@ratings_total = 0
		@ratings_count = 0

		@ratings.each do |rating|
			if rating.rating
				@ratings_total += rating.rating
				@ratings_count += 1
			end
		end

		@rating_average = @ratings_total.to_f / @ratings_count
		@rating_average = @rating_average.round(2)
	end

	def new
		# delete previous comment for this prof from this user
		Rating.where(:prof_name => params[:prof_name], :user_name => session[:user_name]).destroy_all

		@rating = Rating.new
		@rating[:comment] = params[:comment]
		@rating[:rating] = params[:rating]
		@rating[:prof_name] = params[:prof_name]
		@rating[:user_name] = session[:user_name]

		@rating.save

		redirect_to action: "show", prof_name: params[:prof_name]
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	class Prof
	   def initialize(name, rating, commentsCount)
	      @name=name
	      @rating=rating
	      @commentsCount=commentsCount
	   end

	   def commentsCount
	   		@commentsCount
	   end

	   def rating
	   		@rating
	   end

	   def name
	   		@name
	   end
	end

	def index

		@sortedCourses = Course.order(viewCount: :desc)
		
		@nonEmptyView = Array.new
		
		@sortedCourses.each do |course|
			if course.viewCount
				@nonEmptyView.push(course)
			end
		end 

		@sortedbyCart = Course.order(cartCount: :desc)
		@nonEmptyCart = Array.new
		@sortedbyCart.each do |course|
			if course.cartCount
				@nonEmptyCart.push(course)
			end
		end 

		@ratings = Rating.all

		@prof_names = @ratings.uniq.pluck(:prof_name) 

		@profs = Array.new

		@prof_names.each do |prof_name|
			@ratings = Rating.where(prof_name: prof_name)

			@ratings_total = 0
			@ratings_count = 0
			@comments_count = 0

			@ratings.each do |rating|
				if rating.rating
					@ratings_total += rating.rating
					@ratings_count += 1
				end

				if rating.comment != ""
					@comments_count += 1				
				end
			end

			@rating_average = @ratings_total.to_f / @ratings_count
			@rating_average = @rating_average.round(2)

			@profs.push(Prof.new(prof_name, @rating_average, @comments_count))
		end

		@profs_by_comments_count = @profs.sort_by { |prof| [ prof.commentsCount ] }.reverse!

		@profs_by_rating = @profs.clone

		# remove profs with no comments
		@profs_by_comments_count.delete_if do |prof|
			if prof.commentsCount == 0
				true
			else
				false
			end
		end

		# remove profs with NaN rating
		@profs_by_rating.delete_if do |prof|
			if prof.rating.nan?
				true
			else
				false
			end
		end

		@profs_by_rating = @profs_by_rating.sort_by { |prof| [ prof.rating ] }.reverse!
	end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
	
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/prof_helper.rb
module ProfHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sort_helper.rb
module SortHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<body>

	<div class="welcome-wrapper">
		<div class="recommendations-wrapper">
			<p>
			<div class= "recommendation-title"> Popular Courses </div>
			<span class="title-comment">(Most Viewed)</span>
			<br>
			<% if @nonEmptyView.length >= 3 %>
				
				<span class = "course-name"> 
				<%=@nonEmptyView[0].faculty%> 
				<%=@nonEmptyView[0].number %>
				</span> with <%=@nonEmptyView[0].viewCount%> views <br>

				<span class = "course-name"> 
				<%=@nonEmptyView[1].faculty%> 
				<%=@nonEmptyView[1].number %>
				</span> with <%=@nonEmptyView[1].viewCount%> views <br>	

				<span class = "course-name"> 
				<%=@nonEmptyView[2].faculty%> 
				<%=@nonEmptyView[2].number %>
				</span> with <%=@nonEmptyView[2].viewCount%> views <br>

			<% else %>
				Not enough information to show. (Minimum 3 courses must be viewed)
			<% end %>
			</p>

<br>
			<p>
			<div class= "recommendation-title"> Hottest Courses </div>  <span class= "title-comment">(Most Added to Student's Profile)</span>
			<br>
				<% if @nonEmptyCart.length >= 3 %>
				<span class = "course-name"> 
				<%=@nonEmptyCart[0].faculty%> 
				<%=@nonEmptyCart[0].number %>
				</span>with <%=@nonEmptyCart[0].cartCount%> additions <br>

				<span class = "course-name"> 
				<%=@nonEmptyCart[1].faculty%> 
				<%=@nonEmptyCart[1].number %>
				</span> with <%=@nonEmptyCart[1].cartCount%> additions <br>

				<span class = "course-name"> 
				<%=@nonEmptyCart[2].faculty%> 
				<%=@nonEmptyCart[2].number %>
				</span> with <%=@nonEmptyCart[2].cartCount%> additions <br>
			<% else %>
				Not enough information to show.
				(minimum 3 courses must have been added to course cart)
			<% end %>
			</p> <br><br><br>
		</div>

		<%= form_tag sort_path, :method => 'get', :class => 'course-search-form' do %>
			
			<h1 class= "need-background"> <img class="sfu-logo" src="http://www.sfu.ca/~hongweil/images/sfu.png" alt="sfu-logo">
			COURSE SEARCH</h1>
      <table class="course-search" align="center">



        <tr><td>Year:</td>
        <td><%= select_tag :year, options_for_select( Course.all.pluck(:year).uniq ), :style => "width:163px" %>
        </td></tr>

        <tr><td>Semester:</td>
        <td><%= select_tag :semester, options_for_select( Course.all.pluck(:semester).uniq ), :style => "width:163px" %>
        </td></tr>

        <tr><td>Faculty:</td>
        <td> <%= select_tag :faculty, options_for_select( Course.all.pluck(:faculty).uniq.insert(0, "") ), :style => "width:163px" %>
        </td></tr>

        <tr><td>Number:</td><td><%= text_field_tag :number, params[:number] ,:style => "width:153px" %></td></tr>

        <tr><td>Unit:</td><td><%= select_tag :unit, options_for_select( Course.all.pluck(:unit).uniq.sort_by! { |u| u.to_i } ) ,:style => "width:163px" %></td></tr>

        <tr><td>Professor:</td>
        <td> <%= select_tag :instructor, options_for_select( Course.all.pluck(:instructor).uniq.insert(0, "") ), :style => "width:163px" %>
        </td></tr>


        <tr><td>Designation:</td>
        <td> Writing<%= check_box_tag :W, "W" %>
        Quantitative<%= check_box_tag :Q, "Q" %>
        <br>
        Breath &nbsp<%= select_tag :B, options_for_select(["","Breadth", "Breadth-Science",
               "Breadth-Social", "Breadth-Humanities"]),
          :style => "width:103px" %>
        </td></tr>

        <tr><td>Schedule Days:</td>
        <td> 
          Mon<%= check_box_tag :Mon, "Mo" %>
          Tu<%= check_box_tag :Tu, "Tu" %>
          Wed<%= check_box_tag :Wed, "We" %>
          Th<%= check_box_tag :Th, "Th" %>
          Fri<%= check_box_tag :Fri, "Fr" %>
        <br>
    
        </td></tr>

      </table>
			<br>
			<%= submit_tag "Search",  class:"button", :name => "commit" %>
			<%= submit_tag "Search(in WQB order)", class:"button", :name => "commit" %>
		<% end %>
		


		<div class="recommendations-wrapper">
			<p>
			<div class= "recommendation-title"> Best Instructors </div>  <span class= "title-comment">(Highest Rating)</span>
			<br>
				<% if @profs_by_rating.length >= 3 %>
				<span class = "course-name"> 
				<%=@profs_by_rating[0].name%> 
				</span>with <%=@profs_by_rating[0].rating%> <br>

				<span class = "course-name"> 
				<%=@profs_by_rating[1].name%> 
				</span> with <%=@profs_by_rating[1].rating%> <br>

				<span class = "course-name"> 
				<%=@profs_by_rating[2].name%> 
				</span> with <%=@profs_by_rating[2].rating%> <br>
			<% else %>
				Not enough information to show.
				(minimum 3 profs must be rated, only <%=@profs_by_rating.length%> do now)
			<% end %>
			</p>

<br>
			<p>
			<div class= "recommendation-title"> Popular Instructors </div>  <span class= "title-comment">(Most Number of Comments)</span>
			<br>
				<% if @profs_by_comments_count.length >= 3 %>
				<span class = "course-name"> 
				<%=@profs_by_comments_count[0].name%> 
				</span>with <%=@profs_by_comments_count[0].commentsCount%> comments <br>

				<span class = "course-name"> 
				<%=@profs_by_comments_count[1].name%> 
				</span> with <%=@profs_by_comments_count[1].commentsCount%> comments <br>

				<span class = "course-name"> 
				<%=@profs_by_comments_count[2].name%> 
				</span> with <%=@profs_by_comments_count[2].commentsCount%> comments <br>
			<% else %>
				Not enough information to show.
				(minimum 3 profs must have comments, only <%=@profs_by_comments_count.length%> do now)
			<% end %>
			</p>
			<br><br><br>
		</div>
		
	</div>
</body>