config/routes.rb
Rails.application.routes.draw do

  get 'schedule/index'

  get 'schedule/p1'

  get 'schedule/p2'

  get "/courses/sort " => "courses#sort", :as => 'sort'

  get 'prof/index'

  get 'prof/list'

  get 'prof/show'

  get 'prof/new'
  resources :faculties

  resources :courses
  resources  :welcome

  get 'url_construct/index'
  match ':controller(/:action(/:id))', :via => :get
  match ':controller(/:action(/:id))', :via => :post

  get 'admin/new'

  get 'admin/become_admin_attempt'
  post 'admin/become_admin_attempt'

  get 'sessions/login'
  post 'sessions/login_attempt'
  get 'sessions/logout'

  get 'users/login'
  get 'users/new'
  get 'welcome/index'

  resources :users

  root 'welcome#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_and_belongs_to_many :user
  has_many :tutorial

  def self.search(faculty, number, year,semester, unit, prof, w,q,b, mon, tu, wed, th, fri)

    if faculty || number || year || semester || unit || prof ||  w || q || b || mon || tu || wed || th || fri #|| section || instructor || unit

     where(['faculty LIKE ? AND number LIKE ? AND year LIKE ? AND semester LIKE ? AND unit LIKE ? AND instructor LIKE ? AND designation LIKE ?  AND designation LIKE ?  AND designation LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?  AND calender LIKE ?',
      "%#{faculty}%", "%#{number}%", "%#{year}%", "%#{semester}%", "%#{unit}%", "%#{prof}%" ,"%#{w}%" ,"%#{q}%","%#{b}%","%#{mon}%","%#{tu}%","%#{wed}%","%#{th}%","%#{fri}%" ]) #, "%#{unit}%", "%#{designation}%"  ])
    else
      self.all
    end
  end


end

app/models/d_course.rb
class DCourse < ActiveRecord::Base
  belongs_to :DFaculty
end

app/models/d_detail.rb
class DDetail < ActiveRecord::Base
end

app/models/d_faculty.rb
class DFaculty < ActiveRecord::Base
  belongs_to :DSemester
  has_many :DCourses
end

app/models/d_section.rb
class DSection < ActiveRecord::Base
end

app/models/d_semester.rb
class DSemester < ActiveRecord::Base
  belongs_to :DYear
  has_many :DFaculties
end

app/models/d_year.rb
class DYear < ActiveRecord::Base
  has_many :DSemesters
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	 validates_length_of :prof_name, :in => 3..20
	 validates :user_name, :presence => true, :length => { :in => 3..20 }

	 validates :rating, numericality: { only_integer: true, allow_blank: true} 
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  belongs_to :course
  has_and_belongs_to_many :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :course
  has_and_belongs_to_many :tutorial
  attr_accessor :password

  EMAIL_REGEX =  /\A[^@\s]+@([^@.\s]+\.)*[^@.\s]+\z/
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create

  before_save :encrypt_password
  after_save :clear_password
  def encrypt_password
	if password.present?
    	self.salt = BCrypt::Engine.generate_salt
    	self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
  	end
  end

  def clear_password
     self.password = nil
  end

  def self.authenticate(username_or_email="", login_password="")
    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end
    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

end

app/controllers/prof_controller.rb
class ProfController < ApplicationController
  	def index
  		if params[:page]
  			@current_page = params[:page].to_i
  		else
  			@current_page = 1
  		end

		prof_name = params[:prof_name]
		if prof_name
			prof_name.downcase!
		end

		@profs = Course.where("LOWER(instructor) LIKE ?", "%#{prof_name}%")

	  	# get unique instructor names
	  	@profs = @profs.uniq.pluck(:instructor) 
	  	
	  	# sort
	  	@profs = @profs.sort! 

	  	@pages_count = @profs.length / 10.0
	  	@pages_count = @pages_count.ceil

	  	@profs = @profs.drop((@current_page - 1) * 10)
	  	@profs = @profs.take 10
	end

	def list
		prof_name = params[:prof_name]
		if prof_name
			prof_name.downcase!
		end

		@profs = Course.where("LOWER(instructor) LIKE ?", "%#{prof_name}%")

	  	# get unique instructor names
	  	@profs = @profs.uniq.pluck(:instructor) 
	  	
	  	# sort
	  	@profs = @profs.sort!
	end

	def show
		@ratings = Rating.where(prof_name: params[:prof_name])

		@ratings_total = 0
		@ratings_count = 0

		@ratings.each do |rating|
			if rating.rating
				@ratings_total += rating.rating
				@ratings_count += 1
			end
		end

		@rating_average = @ratings_total.to_f / @ratings_count
		@rating_average = @rating_average.round(2)
	end

	def new
		# delete previous comment for this prof from this user
		Rating.where(:prof_name => params[:prof_name], :user_name => session[:user_name]).destroy_all

		@rating = Rating.new
		@rating[:comment] = params[:comment]
		@rating[:rating] = params[:rating]
		@rating[:prof_name] = params[:prof_name]
		@rating[:user_name] = session[:user_name]

		@rating.save

		redirect_to action: "show", prof_name: params[:prof_name]
	end
end

app/controllers/sort_controller.rb
class SortController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
	
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/prof_helper.rb
module ProfHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sort_helper.rb
module SortHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/prof/index.html.erb
<h1 class= "need-background"> <img class="sfu-logo" src="http://www.sfu.ca/~hongweil/images/sfu.png" alt="sfu-logo">SEARCH A PROFESSOR </h1>

<%= form_tag prof_index_path, :method => 'get' do %>
	<table class= "prof-search" align="center">
		<tr><td>Professor name:</td><td><%= text_field_tag :prof_name, params[:prof_name] %>	
		<%= submit_tag "Search", class:"button", :name => nil %></td></tr>
	</table>
	<br>
	
<% end %>

<br>
<% if @pages_count > 1 %>
	<% $i = 1
	while $i <= @pages_count do %>
		<% if $i == @current_page %>
			<%= link_to $i, prof_index_path(page: $i, prof_name: params[:prof_name]), {:class => "page-button current"} %>
		<% else %>
			<%= link_to $i, prof_index_path(page: $i, prof_name: params[:prof_name]), {:class => "page-button"} %>
		<% end %>
		<% $i += 1 %>
	<% end %>
<% end %>
<br>
<div class="table-wrapper">
	<table>
		<tr>
			<th>Professor List</th>
		</tr>
	 
		<% @profs.each do |prof| %>
		    <tr>
		      <td><%= link_to prof, prof_show_path(:prof_name => prof) %></td>
		    </tr>
		<% end %>
	</table>

</div>

app/views/prof/list.html.erb
<h1>Prof#list</h1>
<p>Find me in app/views/prof/list.html.erb</p>

<table>
	<tr>
		<th>Name</th>
	</tr>
 
	<% @profs.each do |prof| %>
	    <tr>
	      <td><%= link_to prof, prof_show_path(:prof_name => prof) %></td>
	    </tr>
	<% end %>
</table>

app/views/prof/show.html.erb
<h1 class="need-background"><img class="sfu-logo2" src="http://www.sfu.ca/~hongweil/images/sfu.png" alt="sfu-logo"> <span class= "prof-name"><%= params[:prof_name] %> </span></h1>
<% if @ratings_count > 0 %>
	<p class= "average-rating">Rating is <b><%= @rating_average %></b> according to <b> <%= @ratings_count %></b> people</p>
<% else %>
	<span>No one gave rating to this professor. Be the first to rate!</span>
<% end %>
 
<% if session[:user_name].present? %>
	<div class="comment-form">
	  <%= form_tag prof_new_path, :method => 'get' do %>
  		Rating: <%= select_tag "rating", options_for_select(["", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]) %>
  		<br>
		Comment:
		<br> 
		<%= text_area_tag :comment %>
		<%= hidden_field_tag 'prof_name', params[:prof_name] %>
		<br>
		<%= submit_tag "Submit", class:"submit-button", :name => nil %>
	<% end %>
	</div>
<% else %>
	<div class="login-notice">You need to be logged in to rate this professor. </div>
<% end %>

<div class="ratings-wrapper"> 
	<% @ratings.each do |rating| %>
		<% if rating.rating
			   @user_rating = rating.rating
		   else
		       @user_rating = "-"
		   end %>

		<div class="rating">
			<div class="rating-user-name"> <b><span class= "name-only"> <%= rating.user_name %></span></b> says</div>
			<span class="rating-comment"><%= rating.comment %></span>	
			<div class="rating-rating">Rating: <%= @user_rating %>/10</div>
			<div class="rating-date"><%= rating.created_at %></div>
	    </div>
	    <br>
	<% end %>
</div>